-- SCRIPT PARA CRIAÇÃO DA TEBELA PRODUTOS
CREATE TABLE PRODUTOS(
	ID					UNIQUEIDENTIFIER		PRIMARY KEY,
	NOME				VARCHAR(150)			NOT NULL,
	PRECO				DECIMAL(10,2)			NOT NULL,
	QUANTIDADE			INTEGER					NOT NULL,
	DATAHORACADASTRO	DATETIME				NOT NULL
);